version: '3.7'

services:
  oracle19c:
    shm_size: '8gb'
    container_name: oracle19c
    tty: true
    restart: "unless-stopped"
    image: lord143/oracledb:19.3.0-ee
    ports:
      - 1521:1521
      - 5500:5500
      - 8081:8081
    volumes:
        - ./setup-scripts:/opt/oracle/scripts/setup
        - ./dump:/opt/oracle/dump
    environment:
        - "ORACLE_PWD=oracle"
        # schema of the dump you want to import
        - "SOURCE_SCHEMA=change-or-delete-me"
        # tablespace of the dump you want to import
        - "SOURCE_TABLESPACE=change-or-delete-me"
        # you may want to exclude `GRANT`: `EXCLUDE=USER,GRANT', if your dump contains them
        # if you dont have anything to exclude, remove the variable
        - "EXCLUDE=user"
    deploy:
      resources:
         limits:
           memory: '3G'
volumes:
  oracle-data: