spring:
    datasource:
        url: jdbc:h2:file:~/test
        driverClassName: org.h2.Driver
        username: sa
        password: sa
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    h2:    
        console.enabled: true

server: 
    port: 8080
   